function setup(){document.documentElement.lang=lang;document.documentElement.dir=lang==='fa'?'rtl':'ltr';$('#lang').textContent=lang==='fa'?'EN':'فا';$('#home').textContent=T('brand');$('#giftTag').textContent=T('giftTag');$('#giftTitle').textContent=T('giftTitle');$('#giftText').textContent=T('giftText');$('#openGift').textContent=T('open')}
function origin(){return origins.find(x=>x[0]===p.origin)||origins[0]}function dn(d){return lang==='fa'?d.fa:d.en}function country(d){return lang==='fa'?d.countryFa:d.country}function rad(x){return x*Math.PI/180}function dist(a,b){const R=6371,dLat=rad(b.lat-a[3]),dLon=rad(b.lon-a[4]),q=Math.sin(dLat/2)**2+Math.cos(rad(a[3]))*Math.cos(rad(b.lat))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(q))}
function estimate(d){const o=origin(),km=dist(o,d),month=new Date(p.start+'T12:00:00').getMonth()+1,season=[6,7,8,12].includes(month)?1.18:1,trav=p.adults+p.children*.72,flight=Math.max(700,(km*.245+620)*season)*trav,night=d.night*({three:.78,four:1,five:1.55,apartment:.86,resort:1.75}[p.stay]||1)*(p.days-1),food=d.food*({budget:.72,balanced:1,premium:1.48}[p.food]||1)*trav*p.days,local=d.local*({none:.7,needed:1,car:1.35,driver:1.8}[p.transport]||1)*p.days,fun=d.act*trav*p.days,total=flight+night+food+local+fun;return{flight,night,food,local,fun,buffer:total*.1,total:total*1.1,hours:Math.max(2,km/780+1.7),km}}
function score(d){let s=45,match=p.styles.filter(x=>d.tags.includes(x)).length;s+=match*11;const e=estimate(d),month=new Date(p.start+'T12:00:00').getMonth()+1;if(d.good.includes(month))s+=8;else s-=5;if(e.total<=p.budget)s+=13;else s-=Math.min(22,(e.total/p.budget-1)*30);if(e.hours<=p.maxHours)s+=8;else s-=Math.min(20,(e.hours-p.maxHours)*2);if(p.flight==='direct'&&origin()[0]!=='DOH')s-=3;if(p.priority==='cost')s-=e.total/1800;if(p.priority==='comfort'&&d.move==='public')s+=5;if(p.priority==='weather'&&d.good.includes(month))s+=7;if(p.mode!=='open'){const w=p.wanted.toLowerCase();if(w.includes(d.en.toLowerCase())||w.includes(d.country.toLowerCase())||w.includes(d.fa))s+=28}return Math.max(1,Math.min(99,Math.round(s)))}
function build(){const ranked=D.map(d=>({...d,score:score(d),e:estimate(d)})).sort((a,b)=>b.score-a.score),fit=ranked[0],practical=[...ranked].sort((a,b)=>(b.score-(b.e.total>p.budget?18:0))-(a.score-(a.e.total>p.budget?18:0)))[0];return{fit,practical,alts:ranked.filter(x=>x.id!==practical.id).slice(0,2)}}
function btn(txt,val,key,multi=false){const sel=multi?(p[key]||[]).includes(val):p[key]===val;return`<button class="choice ${sel?'sel':''}" data-k="${key}" data-v="${val}" data-m="${multi}">${txt}</button>`}function binds(){document.querySelectorAll('[data-k]').forEach(b=>b.onclick=()=>{const k=b.dataset.k,v=b.dataset.v,m=b.dataset.m==='true';if(m){p[k]=p[k]||[];p[k]=p[k].includes(v)?p[k].filter(x=>x!==v):(p[k].length<3?[...p[k],v]:p[k])}else p[k]=v;save();question()})}
function welcome(){view='welcome';step=-1;$('#back').style.visibility='hidden';$('#app').innerHTML=`<section class="hero"><small class="eyebrow">${lang==='fa'?'برای امیر و ساناز':'For Amir & Sanaz'}</small><h1>${T('welcome')}</h1><p>${T('welcomeText')}</p><div class="route"><span>${origin()[0]}</span><i></i><span>?</span></div><button class="primary" id="start">${T('start')}</button></section><section class="card"><b>🔒 ${lang==='fa'?'بدون حساب کاربری؛ جواب‌ها روی همین دستگاه می‌مانند.':'No account required; answers stay on this device.'}</b></section>`;$('#bottom').innerHTML='';$('#start').onclick=()=>{step=0;view='wizard';question()}}
function collect(){if(step===0){p.origin=$('#origin').value;p.adults=+$('#adults').value;p.children=+$('#children').value}if(step===1){p.passport=$('#passport').value;p.passportExpiry=$('#passExp').value;p.secondPassport=$('#second').value;p.resCountry=$('#resCountry')?.value||'';p.resExpiry=$('#resExp')?.value||''}if(step===2){p.start=$('#date').value;p.days=+$('#days').value;p.budget=+$('#budget').value}if(step===3)p.wanted=$('#wanted').value;if(step===5)p.maxHours=+$('#hours').value;if(step===7)p.halal=$('#halal').checked;save()}
function question(){setup();view='wizard';$('#back').style.visibility=step>0?'visible':'hidden';const q=F[lang].q[step];let b='';if(step===0)b=`<label class="field">${lang==='fa'?'فرودگاه مبدأ':'Origin airport'}</label><select id="origin" class="input">${origins.map(x=>`<option value="${x[0]}" ${p.origin===x[0]?'selected':''}>${x[0]} — ${lang==='fa'?x[2]:x[1]}</option>`).join('')}</select><div class="grid"><div><label class="field">${lang==='fa'?'بزرگسال':'Adults'}</label><input id="adults" class="input" type="number" min="1" max="8" value="${p.adults}"></div><div><label class="field">${lang==='fa'?'کودک':'Children'}</label><input id="children" class="input" type="number" min="0" max="6" value="${p.children}"></div></div>`;
